// <auto-generated />
using System;
using MessManagementSystem.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MessManagementSystem.Api.Migrations
{
    [DbContext(typeof(MessDbContext))]
    [Migration("20260826155908_AddMessAndMemberMessRelationship")]
    partial class AddMessAndMemberMessRelationship
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("MessManagementSystem.Api.Models.Member", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("JoinDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("MessId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("MessId");

                    b.ToTable("Members");
                });

            modelBuilder.Entity("MessManagementSystem.Api.Models.Mess", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AdminMemberId")
                        .HasColumnType("int");

                    b.Property<string>("MessCode")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("AdminMemberId")
                        .IsUnique();

                    b.HasIndex("MessCode")
                        .IsUnique();

                    b.ToTable("Messes");
                });

            modelBuilder.Entity("MessManagementSystem.Api.Models.Member", b =>
                {
                    b.HasOne("MessManagementSystem.Api.Models.Mess", "Mess")
                        .WithMany("Members")
                        .HasForeignKey("MessId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Mess");
                });

            modelBuilder.Entity("MessManagementSystem.Api.Models.Mess", b =>
                {
                    b.HasOne("MessManagementSystem.Api.Models.Member", "AdminMember")
                        .WithOne()
                        .HasForeignKey("MessManagementSystem.Api.Models.Mess", "AdminMemberId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AdminMember");
                });

            modelBuilder.Entity("MessManagementSystem.Api.Models.Mess", b =>
                {
                    b.Navigation("Members");
                });
#pragma warning restore 612, 618
        }
    }
}
