// <auto-generated />
using System;
using MessManagementSystem.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MessManagementSystem.Api.Migrations
{
    [DbContext(typeof(MessDbContext))]
    partial class MessDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("MessManagementSystem.Api.Models.Expense", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("ExpenseDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("MemberId")
                        .HasColumnType("int");

                    b.Property<int>("MessId")
                        .HasColumnType("int");

                    b.Property<int>("RecordedBy")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MemberId");

                    b.HasIndex("MessId");

                    b.HasIndex("RecordedBy");

                    b.ToTable("Expenses");
                });

            modelBuilder.Entity("MessManagementSystem.Api.Models.Meal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Breakfast")
                        .HasColumnType("int");

                    b.Property<int>("Dinner")
                        .HasColumnType("int");

                    b.Property<int>("Lunch")
                        .HasColumnType("int");

                    b.Property<DateTime>("MealDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("MemberId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MemberId", "MealDate")
                        .IsUnique();

                    b.ToTable("Meals");
                });

            modelBuilder.Entity("MessManagementSystem.Api.Models.Member", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("JoinDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("MessId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("MessId");

                    b.ToTable("Members");
                });

            modelBuilder.Entity("MessManagementSystem.Api.Models.MemberCashTransfer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(65,30)");

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("MemberId")
                        .HasColumnType("int");

                    b.Property<int>("MessId")
                        .HasColumnType("int");

                    b.Property<int>("RecordedBy")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("TransferDate")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("MemberId");

                    b.HasIndex("MessId");

                    b.HasIndex("RecordedBy");

                    b.ToTable("MemberCashTransfers");
                });

            modelBuilder.Entity("MessManagementSystem.Api.Models.MemberPayment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("MemberId")
                        .HasColumnType("int");

                    b.Property<int>("MessId")
                        .HasColumnType("int");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("RecordedBy")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MemberId");

                    b.HasIndex("MessId");

                    b.HasIndex("RecordedBy");

                    b.ToTable("MemberPayments");
                });

            modelBuilder.Entity("MessManagementSystem.Api.Models.Mess", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AdminMemberId")
                        .HasColumnType("int");

                    b.Property<string>("MessCode")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("AdminMemberId")
                        .IsUnique();

                    b.HasIndex("MessCode")
                        .IsUnique();

                    b.ToTable("Messes");
                });

            modelBuilder.Entity("MessManagementSystem.Api.Models.MessJoinRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("MemberId")
                        .HasColumnType("int");

                    b.Property<int>("MessId")
                        .HasColumnType("int");

                    b.Property<int?>("MessId1")
                        .HasColumnType("int");

                    b.Property<DateTime>("RequestDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("MemberId");

                    b.HasIndex("MessId");

                    b.HasIndex("MessId1");

                    b.ToTable("MessJoinRequests");
                });

            modelBuilder.Entity("MessManagementSystem.Api.Models.Expense", b =>
                {
                    b.HasOne("MessManagementSystem.Api.Models.Member", "Member")
                        .WithMany()
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MessManagementSystem.Api.Models.Mess", "Mess")
                        .WithMany("Expenses")
                        .HasForeignKey("MessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MessManagementSystem.Api.Models.Member", "RecordedByMember")
                        .WithMany("RecordedExpenses")
                        .HasForeignKey("RecordedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Member");

                    b.Navigation("Mess");

                    b.Navigation("RecordedByMember");
                });

            modelBuilder.Entity("MessManagementSystem.Api.Models.Meal", b =>
                {
                    b.HasOne("MessManagementSystem.Api.Models.Member", "Member")
                        .WithMany()
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Member");
                });

            modelBuilder.Entity("MessManagementSystem.Api.Models.Member", b =>
                {
                    b.HasOne("MessManagementSystem.Api.Models.Mess", "Mess")
                        .WithMany("Members")
                        .HasForeignKey("MessId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Mess");
                });

            modelBuilder.Entity("MessManagementSystem.Api.Models.MemberCashTransfer", b =>
                {
                    b.HasOne("MessManagementSystem.Api.Models.Member", "Member")
                        .WithMany("CashTransfers")
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MessManagementSystem.Api.Models.Mess", "Mess")
                        .WithMany("MemberCashTransfers")
                        .HasForeignKey("MessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MessManagementSystem.Api.Models.Member", "RecordedByMember")
                        .WithMany("RecordedCashTransfers")
                        .HasForeignKey("RecordedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Member");

                    b.Navigation("Mess");

                    b.Navigation("RecordedByMember");
                });

            modelBuilder.Entity("MessManagementSystem.Api.Models.MemberPayment", b =>
                {
                    b.HasOne("MessManagementSystem.Api.Models.Member", "Member")
                        .WithMany("Payments")
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MessManagementSystem.Api.Models.Mess", "Mess")
                        .WithMany("MemberPayments")
                        .HasForeignKey("MessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MessManagementSystem.Api.Models.Member", "RecordedByMember")
                        .WithMany("RecordedPayments")
                        .HasForeignKey("RecordedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Member");

                    b.Navigation("Mess");

                    b.Navigation("RecordedByMember");
                });

            modelBuilder.Entity("MessManagementSystem.Api.Models.Mess", b =>
                {
                    b.HasOne("MessManagementSystem.Api.Models.Member", "AdminMember")
                        .WithOne("AdminMess")
                        .HasForeignKey("MessManagementSystem.Api.Models.Mess", "AdminMemberId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AdminMember");
                });

            modelBuilder.Entity("MessManagementSystem.Api.Models.MessJoinRequest", b =>
                {
                    b.HasOne("MessManagementSystem.Api.Models.Member", "Member")
                        .WithMany()
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MessManagementSystem.Api.Models.Mess", "Mess")
                        .WithMany()
                        .HasForeignKey("MessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MessManagementSystem.Api.Models.Mess", null)
                        .WithMany("JoinRequests")
                        .HasForeignKey("MessId1");

                    b.Navigation("Member");

                    b.Navigation("Mess");
                });

            modelBuilder.Entity("MessManagementSystem.Api.Models.Member", b =>
                {
                    b.Navigation("AdminMess");

                    b.Navigation("CashTransfers");

                    b.Navigation("Payments");

                    b.Navigation("RecordedCashTransfers");

                    b.Navigation("RecordedExpenses");

                    b.Navigation("RecordedPayments");
                });

            modelBuilder.Entity("MessManagementSystem.Api.Models.Mess", b =>
                {
                    b.Navigation("Expenses");

                    b.Navigation("JoinRequests");

                    b.Navigation("MemberCashTransfers");

                    b.Navigation("MemberPayments");

                    b.Navigation("Members");
                });
#pragma warning restore 612, 618
        }
    }
}
